### PR TITLE
Convert to es6

### PR DESCRIPTION
**Pull request by jescalan**
Work in progress, untested

### CODE REVIEW

**Comment by djeglin** [comment]
Does using `const` for `fetchedPages` in the worker not make it immutable? That array gets pushed to as the worker runs as a second failsafe to make sure it isn't fetching the same page multiple times (this is done in the main thread script as well, but I added it to the worker as well in case of there being duplicate links in the same page that would be assigned to the worker before it had returned results. 

Come to think of it, `fetchedPages` is only being pushed to when the promise resolves at the moment, which doesn't stop this right now. Maybe the push needs to happen when the request is fired off, rather than when it resolves. We can always remove the item from `fetchedPages` if the request errors. 

Would suggest using `let` instead of `const` here, anyway.

**Comment by jescalan** [comment]
Yup, this was just a quick run to lay down the base. `const` makes it such that you cannot reassign the variable. So for example if you have a `const` thats an array you can still push/pop, but you can't re-assign the base variable. If that variable needs to be re-assigned definitely change to a `let`!

**Comment by jescalan** [comment]
Ok so I think a good next step would be to fill in the readme with some usage instructions 😁

**Comment by jescalan** [comment]
Woah, quick merge. Did you test this and make sure it's working?

**Pull request merged**
